spring:
  redis:
    host: 60.205.182.158
    port: 6379
    timeout: 60s
    password:
    lettuce:
      pool:
        max-active: 500
        max-idle: 100
        min-idle: 20
        max-wait: -1ms
    database: 0
  application:
    name: devops
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid: # 2.2.3开始提供全局druid参数，以下是默认值和druid原生保持一致
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      primary: at_master #记得设置一个默认数据源
      datasource:
        at_master:
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.162.223:3306/at_master?characterEncoding=utf8&useSSL=false
        #          druid: # 以下参数针对每个库可以重新设置druid参数
        #            initial-size:
        #            max-active:
        #            min-idle:
        #            max-wait:
        #            min-evictable-idle-time-millis:
        #            max-evictable-idle-time-millis:
        #            time-between-eviction-runs-millis:
        #            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
        #            validation-query-timeout:
        #            test-on-borrow:
        #            test-on-return:
        #            test-while-idle:
        #            pool-prepared-statements:
        #            max-open-prepared-statements:
        #            filters:
        #            share-prepared-statements:
        at_slave:
          username: root
          password: 19871021
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.162.223:3306/at_slave?characterEncoding=utf8&useSSL=false
  cache:
    type: redis
    redis:
      time-to-live: 1800s  #缓存超时时间ms
      cache-null-values: false  #是否缓存空值

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置
  type-aliases-package: com.msw.devops.entity  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
  global-config:
    refresh: true  # 是否自动刷新 Mapper 对应的 XML 文件，默认不自动刷新。如果配置了该属性，Mapper 对应的 XML 文件会自动刷新，更改 XML 文件后，无需再次重启工程，由此节省大量时间. 该配置不建议在生产环境打开
logging:
  level:
    com.msw.devops: debug
