spring:
  datasource:
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid: # 2.2.3开始提供全局druid参数，以下是默认值和druid原生保持一致
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      primary: atdb #记得设置一个默认数据源
      datasource:
        atdb:
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.100.20.186:3306/dynamic?characterEncoding=utf8&useSSL=false
#          druid: # 以下参数针对每个库可以重新设置druid参数
#            initial-size:
#            max-active:
#            min-idle:
#            max-wait:
#            min-evictable-idle-time-millis:
#            max-evictable-idle-time-millis:
#            time-between-eviction-runs-millis:
#            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
#            validation-query-timeout:
#            test-on-borrow:
#            test-on-return:
#            test-while-idle:
#            pool-prepared-statements:
#            max-open-prepared-statements:
#            filters:
#            share-prepared-statements:
        easydb:
          username: root
          password: 123456
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.100.20.186:3307/dynamic?characterEncoding=utf8&useSSL=false
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml  # MyBatis Mapper 所对应的 XML 文件位置，如果您在 Mapper 中有自定义方法（XML 中有自定义实现），需要进行该配置，告诉 Mapper 所对应的 XML 文件位置
  type-aliases-package: com.msw.devops.entity  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名（即 XML 中调用的时候不用包含包名）
logging:
  level:
    com.msw.devops: debug
